apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ignite.fullname" . }}-configmap
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <!--
        Licensed to the Apache Software Foundation (ASF) under one or more
        contributor license agreements.  See the NOTICE file distributed with
        this work for additional information regarding copyright ownership.
        The ASF licenses this file to You under the Apache License, Version 2.0
        (the "License"); you may not use this file except in compliance with
        the License.  You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    -->

    <Configuration monitorInterval="60">
        <Appenders>
            <Console name="CONSOLE" target="SYSTEM_OUT">
                <PatternLayout pattern="[%d{ISO8601}][%-5p][%t][%c{1}]%notEmpty{[%markerSimpleName]} %m%n"/>
                <ThresholdFilter level="ERROR" onMatch="DENY" onMismatch="ACCEPT"/>
            </Console>

            <Console name="CONSOLE_ERR" target="SYSTEM_ERR">
                <PatternLayout pattern="[%d{ISO8601}][%-5p][%t][%c{1}]%notEmpty{[%markerSimpleName]} %m%n"/>
            </Console>

            <Routing name="FILE">
                <Routes pattern="$${sys:nodeId}">
                    <Route>
                        <RollingFile name="Rolling-${sys:nodeId}" fileName="${sys:IGNITE_HOME}/work/log/ignite-${sys:nodeId}.log"
                                    filePattern="${sys:IGNITE_HOME}/work/log/ignite-${sys:nodeId}-%i-%d{yyyy-MM-dd}.log.gz">
                            <PatternLayout pattern="[%d{ISO8601}][%-5p][%t][%c{1}]%notEmpty{[%markerSimpleName]} %m%n"/>
                            <Policies>
                                <TimeBasedTriggeringPolicy interval="6" modulate="true" />
                                <SizeBasedTriggeringPolicy size="10 MB" />
                            </Policies>
                        </RollingFile>
                    </Route>
                </Routes>
            </Routing>
        </Appenders>

        <Loggers>
            <!--
            <Logger name="org.apache.ignite" level=DEBUG/>
            -->

            <!--
                Uncomment to disable courtesy notices, such as SPI configuration
                consistency warnings.
            -->
            <!--
            <Logger name="org.apache.ignite.CourtesyConfigNotice" level=OFF/>
            -->

            <Logger name="org.springframework" level="WARN"/>
            <Logger name="org.eclipse.jetty" level="WARN"/>

            <!--
            Avoid warnings about failed bind attempt when multiple nodes running on the same host.
            -->
            <Logger name="org.eclipse.jetty.util.log" level="ERROR"/>
            <Logger name="org.eclipse.jetty.util.component" level="ERROR"/>

            <Logger name="com.amazonaws" level="WARN"/>

            <Root level="INFO">
                <!-- Uncomment to enable logging to console. -->
                <!--
                <AppenderRef ref="CONSOLE" level="DEBUG"/>
                -->

                <AppenderRef ref="CONSOLE_ERR" level="ERROR"/>
                <AppenderRef ref="FILE" level="DEBUG"/>
            </Root>
        </Loggers>
    </Configuration>
  ignite-config.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <!--
      Licensed to the Apache Software Foundation (ASF) under one or more
      contributor license agreements.  See the NOTICE file distributed with
      this work for additional information regarding copyright ownership.
      The ASF licenses this file to You under the Apache License, Version 2.0
      (the "License"); you may not use this file except in compliance with
      the License.  You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    -->

    <!--
        Configuration example with Kubernetes IP finder and Ignite persistence enabled.
        WAL files and database files are stored in separate disk drives.
    -->
    <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="
            http://www.springframework.org/schema/beans
            http://www.springframework.org/schema/beans/spring-beans.xsd">

        <bean class="org.apache.ignite.configuration.IgniteConfiguration">
            <property name="gridLogger">
                <bean class="org.apache.ignite.logger.log4j2.Log4J2Logger">
                <constructor-arg type="java.lang.String" value="/opt/ignite/apache-ignite/config/log4j2.xml"/>
                </bean>
            </property>

            <property name="peerClassLoadingEnabled" value="{{ .Values.peerClassLoadingEnabled | default false }}"/>

            {{- with .Values.lifecycleBeans }}
            <property name="lifecycleBeans">
                <list>
                    {{- range . }}
                    <bean class="{{ . }}"/>
                    {{- end }}
                </list>
            </property>
            {{- end }}

{{- if (.Values.persistence.enabled) }}
            <!-- Enabling Apache Ignite Persistent Store. -->
            <property name="dataStorageConfiguration">
                <bean class="org.apache.ignite.configuration.DataStorageConfiguration">

                    <property name="defaultDataRegionConfiguration">
                        <bean class="org.apache.ignite.configuration.DataRegionConfiguration">
                            <property name="persistenceEnabled" value="true"/>
                        </bean>
                    </property>

                    <!--
                       Sets a path to the root directory where data and indexes are
                       to be persisted. It's assumed the directory is on a dedicated disk.
                    -->
                    <property name="storagePath" value="/persistence"/>

                    <!--
                        Sets a path to the directory where WAL is stored.
                        It's assumed the directory is on a dedicated disk.
                    -->
                    <property name="walPath" value="/wal"/>

                    <!--
                        Sets a path to the directory where WAL archive is stored.
                        It's assumed the directory is on the same drive with the WAL files.
                    -->
                    <property name="walArchivePath" value="/wal/archive"/>
                </bean>
            </property>

{{- end }}
            <!-- Explicitly configure TCP discovery SPI to provide list of initial nodes. -->
            <property name="discoverySpi">
                <bean class="org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi">
                    <property name="ipFinder">
                        <!--
                            Enables Kubernetes IP finder and setting custom namespace and service names.
                        -->
                        <bean class="org.apache.ignite.spi.discovery.tcp.ipfinder.kubernetes.TcpDiscoveryKubernetesIpFinder">
                            <property name="namespace" value="{{ .Release.Namespace }}"/>
                            <property name="serviceName" value="{{ include "ignite.serviceName" . }}"/>
                        </bean>
                    </property>
                </bean>
            </property>
        </bean>
    </beans>
